{{- if .Values.Orchestration == 'eksctl' -}}
    apiVersion: secrets-store.csi.x-k8s.io/v1
    kind: SecretProviderClass
    metadata:
    name: {{ .Values.Secret.Name }}
    spec:
    provider: aws
    secretObjects:
        - secretName: {{ .Values.Secret.Name }}
        type: Opaque
        data:
            {{- range .Values.Secret.Vars }}
            - objectName: {{ . }}
              key: {{ . }}
            {{- end }}
    parameters:
        objects:
            - objectName: {{ .Values.ARN }}
              jmesPath: |-
              {{- range .Values.Secret.Vars }}
                - path: {{ . }}
                  objectAlias: {{ . }}
              {{- end }}
{{- else if .Values.Orchestration == 'terraform' -}}
    apiVersion: kubernetes-client.io/v1
    kind: ExternalSecret
    metadata:
    name: {{ .Values.Secret.Name }}
    spec:
        backendType: secretsManager
        region: {{ .Values.region }}
        dataFrom:
            - {{ .Values.Secret.Location }}
{{- end -}}