{{- if .Values.Orchestration == 'eksctl' -}}
    apiVersion: secrets-store.csi.x-k8s.io/v1
    kind: SecretProviderClass
    metadata:
    name: {{ .Values.Secret.Name }}
    spec:
    provider: aws
    secretObjects:
        - secretName: {{ .Values.Secret.Name }}
        type: Opaque
        data:
            {{- range .Values.Secret.Vars }}
            - objectName: {{ . }}
              key: {{ . }}
            {{- end }}
    parameters:
        objects:
            - objectName: {{ .Values.ARN }}
              jmesPath: |-
              {{- range .Values.Secret.Vars }}
                - path: {{ . }}
                  objectAlias: {{ . }}
              {{- end }}
            # - path: db_username
            #     objectAlias: db_username
            # - path: db_password
            #     objectAlias: db_password
            # - path: app_user_access_key
            #     objectAlias: app_user_access_key
            # - path: app_user_secret_key
            #     objectAlias: app_user_secret_key
            # - path: jwt_secret_key
            #     objectAlias: jwt_secret_key
            # - path: encrypt_secret_key
            #     objectAlias: encrypt_secret_key
{{- else if .Values.Orchestration == 'terraform' -}}
    apiVersion: kubernetes-client.io/v1
    kind: ExternalSecret
    metadata:
    name: {{ .Values.Secret.Name }}
    spec:
        backendType: secretsManager
        # optional: specify role to assume when retrieving the data
        # roleArn: arn:aws:iam::123456789012:role/test-role
        # optional: specify region
        region: {{ .Values.region }}
        dataFrom:
            - {{ .Values.Secret.Location }}
        # data:
        #     {{- range .Values.SecretVars }}
        #     - key: {{ $.Values.secretname }}
        #       name: {{ . }}
        #       property: {{ . }}
        #     {{- end }}
            # - key: hello-service/credentials
            #   name: password
            #   property: password
            # - key: hello-service/credentials
            #   name: username
            #   property: username
            # - key: hello-service/credentials
            #   name: password_previous
            # # Version Stage in Secrets Manager
            #   versionStage: AWSPREVIOUS
            #   property: password
            # - key: hello-service/credentials
            #   name: password_versioned
            # # Version ID in Secrets Manager
            #   versionId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
            #   property: password
    # {{- else -}}
{{- end -}}