version: '3.9'

services:
# database
  mysql-db:
    user: root
    image: 'mysql'
    restart: 'always'
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: hippopotamus@1
      MYSQL_DATABASE: alinedb
    expose:
      - 3306
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - dbdata:/var/lib/mysql
    networks:
      - aline
  # adminer:
  #   image: 'adminer'
  #   restart: 'always'
  #   ports:
  #     - '8084:8080'
  #   networks:
  #     - aline
# gateway
  gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    image: 'aline-gateway'
    hostname: gateway
    env_file:
      - .env
    environment:
      APP_PORT: 8080
      APP_SERVICE_HOST: localhost
    networks:
      - aline
    expose:
      - 8080
    ports:
      - 8080:8080
# microservices
  underwriter-microservice:
    build:
      context: ./backend/bank
      dockerfile: Dockerfile
    image: 'underwriter'
    container_name: underwriter
    depends_on:
      - mysql-db
    env_file:
      - .env
    environment:
      APP_PORT: 8071
    expose:
      - 8071
    ports:
      - 8071:8071
    networks:
      - aline
  bank-microservice:
    build:
      context: ./backend/bank
      dockerfile: Dockerfile
    image: 'bank'
    container_name: bank
    depends_on:
      - mysql-db
    env_file: .env
    environment: 
      APP_PORT: 8083
    expose:
      - 8083
    ports:
      - 8083:8083
    networks:
      - aline
  transaction-microservice:
    build:
      context: ./backend/transaction
      dockerfile: Dockerfile
    image: 'transaction'
    container_name: transaction
    depends_on:
      - mysql-db
    env_file: .env
    environment:
      APP_PORT: 8073
    expose:
      - 8073
    ports:
      - 8073:8073
    networks:
      - aline
  user-microservice:
    build:
      context: ./backend/user
      dockerfile: Dockerfile
    image: 'user'
    container_name: user
    depends_on:
      - mysql-db
    env_file: .env
    environment:
      APP_PORT: 8070
    expose:
      - 8070
    ports:
      - 8070:8070
    networks:
      - aline
# TODO frontend

volumes:
  dbdata: 

networks:
  aline:
    driver: bridge
    name: aline
    ipam: 
      config:
          - subnet: 172.31.0.0/16
            gateway: "172.31.0.1"