pipeline {
  agent { label 'linux && terraform' }
  tools {
    terraform 'Terraform1.1.8'
  }
  environment {
    WORKING_DIR = 'terraform/'
    REGION = 'us-west-1'
  }
  stages{
    stage('Init') {
      steps {
        withAWS(credentials:'terraform') {
          dir("$WORKING_DIR") {
            sh 'terraform init -backend-config=backend.hcl'
          }
        }
      }
    }
    // stage('Set TF Vars') {
    //   steps {}
    // }
    stage('Get TFVars') {
      steps {
        withAWS(credentials:'terraform', region:"${env.TERRAFORM_S3_REGION}") {
          s3Download(file: "${WORKING_DIR}/terraform.tfvars", bucket: "${env.TFVARS}", path: 'terraform.tfvars')
        }
      }
    }
    stage('Plan') {
      steps {
        withAWS(credentials:'terraform', region:"${REGION}") {
          sh 'ls'
          dir("${WORKING_DIR}") {
            sh 'ls'
            sh 'terraform plan --var-file=terraform.tfvars'
          }
        }
      }
    }
    stage('SonarQube analysis') {
      steps {
        script {
          withSonarQubeEnv('sonarqube') {
            sh "${tool("sonarscan")}/bin/sonar-scanner -Dsonar.projectKey=terraform -Dsonar.sources=terraform"
          }
        }
      }
    }
    stage("Quality gate") {
      steps {
        
        timeout(time: 5, unit: 'MINUTES') {
            // Parameter indicates whether to set pipeline to UNSTABLE if Quality Gate fails
            // true = set pipeline to UNSTABLE, false = don't
            waitForQualityGate(abortPipeline: true)
        }
        
      }
    }
    // stage('Deploy') {
    //   steps {
    //     withAWS(credentials:'terraform') {
    //         sh 'terraform apply -auto-approve'
    //       }
    //     }
    // }
  }
  post {
    always {
      cleanWs()
    }
  }
}