apiVersion: v1
kind: Secret
metadata:
  name: ms-secrets
type: Opaque
# data:
#   ENCRYPT_SECRET_KEY: Y1FmVGhXbVpxNHQ3d0MqRi1KYU5kUmdVa1huMnIK
#   JWT_SECRET_KEY: MjFiNDA1NGEtMWM3NS00ZThhLWFhY2QtOTNhYWFhZDkyZTE5Cg==
#   APP_USER_ACCESS_KEY: NkI1ODcwMzI3MzM1NzYzODc5MkY0MjNGNDUyODQ4MkI0RDYyNTE2NTU0Njg1NjZENTk3MTMzNzQzNjc3Mzk3QQo=
#   APP_USER_SECRET_KEY: MkY0MTI1NDQyQTQ3MkQ0QjYxNTA2NDUzNjc1NjZCNTk3MDMzNzMzNjc2Mzk3OTI0NDIyNjQ1Mjg0ODJCNEQ2Mgo=
stringData:
  ENCRYPT_SECRET_KEY: cQfThWmZq4t7w!z%C*F-JaNdRgUkXn2r
  JWT_SECRET_KEY: 21b4054a-1c75-4e8a-aacd-93aaaad92e19
  APP_USER_ACCESS_KEY: 6B58703273357638792F423F4528482B4D6251655468566D597133743677397A
  APP_USER_SECRET_KEY: 2F4125442A472D4B6150645367566B59703373367639792442264528482B4D62