apiVersion: v1
kind: Service
metadata:
  name: bank-ms
spec:
  selector:
    app: bank-ms
  ports:
  - port: 8083
    targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-ms
spec:
  selector:
    matchLabels:
      app: bank-ms
  template:
    metadata:
      labels:
        app: bank-ms
    spec:
      containers:
      - name: bank-ms
        image: bank
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083

