apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8070
        env:
        - name: APP_PORT
          value: "8070"
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: portal-config
        - secretRef:
            name: db-secrets
        - secretRef:
            name: ms-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
  - port: 8070
    targetPort: 8070        

