apiVersion: v1
kind: Service
metadata:
  name: transaction-ms
spec:
  selector:
    app: transaction-ms
  ports:
  - port: 8073
    targetPort: 8073
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-ms
spec:
  selector:
    matchLabels:
      app: transaction-ms
  template:
    metadata:
      labels:
        app: transaction-ms
    spec:
      containers:
      - name: transaction-ms
        image: transaction
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8073

