apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aline-user
  name: aline-user
spec:
  selector:
    matchLabels:
      app: aline-user
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aline-user
    spec:
      containers:
        - name: aline-user
          image: user
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8070
          env:
          - name: APP_PORT
            value: "8070"
          envFrom:
          - configMapRef:
              name: db-config
          - configMapRef:
              name: portal-config
          - secretRef:
              name: db-secrets
          - secretRef:
              name: ms-secrets
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: aline-user
spec:
  ports:
    - port: 8070
  selector:
    app: aline-user
