apiVersion: v1
kind: Service
metadata:
  name: user-ms
spec:
  selector:
    app: user-ms
  ports:
  - port: 8070
    targetPort: 8070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ms
spec:
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms
    spec:
      containers:
      - name: user-ms
        image: user
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8070

