x-aws-vpc: ${AWS_VPC}
x-aws-security-group: ${SEC_GRP}
x-aws-loadbalancer: ${LOAD_BAL}
version: '3.9'

services:
  nginx:
    image: ${ECR_REPO}/nginx-dl
    ports:
      - "80:80"
    restart: on-failure:3

  aline-underwriter:
    image: ${ECR_REPO}/aline-underwriter-microservice-dl:0.1.0
    container_name: aline-underwriter
    environment:
      APP_PORT: 8071
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    restart: on-failure:3
    secrets:
      - db_keys
    networks:
      - default
  
  aline-bank:
    image: ${ECR_REPO}/aline-bank-microservice-dl:0.1.0
    container_name: aline-bank
    environment: 
      APP_PORT: 8083
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    restart: on-failure:3
    secrets:
      - db_keys
    networks:
      - default

  aline-transaction:
    image: ${ECR_REPO}/aline-transaction-microservice-dl:0.1.0
    container_name: aline-transaction
    environment:
      APP_PORT: 8073
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    restart: on-failure:3
    secrets:
      - db_keys
    networks:
      - default

  aline-user:
    image: ${ECR_REPO}/aline-user-microservice-dl:0.1.0
    container_name: aline-user
    environment:
      APP_PORT: 8070
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    restart: on-failure:3
    secrets:
      - db_keys
    networks:
      - default

secrets:
  db_keys:
    name: "${SECRET_ARN}"
    external: true
    x-aws-keys:
      - "dbuser"
      - "dbpassword"
      - "app_user_access_key"
      - "app_user_secret_key"
      - "jwt_secret_key"
      - "encrypt_secret_key"
