localDeployment: true
Orchestration: eksctl
Repo: INVALID # public.ecr.aws/l4g0u1s9
Secret:
  Name: INVALID
  Location: INVALID
  ARN: INVALID
  Vars:
    - db_username
    - db_password
    - app_user_access_key
    - app_user_secret_key
    - jwt_secret_key
    - encrypt_secret_key
Services:
  - name: aline-bank
    image: aline-bank-dl
    container:
      name: aline-bank
      port: 8083
      path: '/(members|banks|branches).*'
  - name: aline-transaction
    image: aline-transaction
    container:
      name: aline-transaction
      port: 8073
      path: '/(transactions/?.*|(members|accounts)/.+/transactions)'
  - name: aline-underwriter
    image: aline-underwriter
    container:
      name: aline-underwriter
      port: 8071
      path: '/(applicants|applications).*'
  - name: aline-user
    image: aline-user
    container:
      name: aline-user
      port: 8070
      path: '/(users|login).*'